//! `bench fees` — measure bond + transaction fee per `MusicalWork::deposit`.
//!
//! Records are bundled into `pallet_utility::batch_all` calls of
//! `--batch-size` deposits each (default 100, same scheme as `seed` /
//! `bench throughput`). Each inner deposit emits its own `Deposited` event
//! so per-record `bond` / `base_bond` stay accurate, but the runtime only
//! emits one `TransactionFeePaid` for the outer extrinsic — the report
//! amortises that fee across the batch's records. With batch_size=1 the
//! outer extrinsic is still a `batch_all` of one inner call, so `tx_fee`
//! is the outer-extrinsic fee and includes the small batch dispatch
//! overhead (one or two plancks at most).
//!
//! The economic model (`docs/economics.md`) splits the held bond into:
//! - `base_bond` — the unmultiplied `DepositBase + DepositPerByte × size`,
//!   refunded in full by `remove_own` within the 7-day commitment window.
//! - `premium` — the surplus generated by the dynamic multipliers
//!   (`M_fast × M_slow`), permanently transferred to the Treasury at
//!   `remove_own` or `finalize` time.
//!
//! The report exposes both halves and the corresponding total user cost,
//! plus a snapshot of the multipliers and weekly load taken at the start
//! and end of the run, so the reader can reason about the refundable vs.
//! permanent components of the deposit independently of the live
//! multiplier state.
//!
//! Submission is sequential **per signer** (Substrate enforces strictly
//! increasing nonces per account, so pipelining within a signer would race
//! the runtime). With `--signer-count` > 1, signers run concurrently up to
//! `--concurrency`, which is the realistic shape: on a live chain, deposits
//! land in concurrent blocks under non-trivial fee multiplier drift. The
//! measurement variance that this introduces is itself part of the signal.
//!
//! On batch failure the responsible worker exits (mirrors `seed` /
//! `throughput`) — a failed batch typically means broken nonce / funding
//! state, and continuing the same worker would just compound the error.
//! Surviving signers keep draining their partitions.
//!
//! Output is a markdown report grouped by payload-size buckets plus an
//! overall-percentile summary, suitable for committing to a PR or pasting
//! into a tuning discussion. Use `bench throughput` for aggregate-rate
//! measurements; the two answer distinct questions and should not be folded
//! together.

use std::{
    fmt::Write as _,
    path::{Path, PathBuf},
    sync::Arc,
    time::Instant,
};

use anyhow::{Result, anyhow};
use midds_client::{PricingSnapshot, fixed_u128_to_f64};
use midds_fixtures::{identifiers::iswc_for_index, musical_work, pathological, rng::seeded_rng};
use midds_types::MusicalWork;
use parity_scale_codec::Encode;
use rand::Rng;
use tokio::{sync::Semaphore, task::JoinSet};

use crate::{
    bench::{
        util::{mean, percentile, sanitize_signer_concurrency, write_report_to},
        worker::{
            RunnerHandles, RunnerInputs, fetch_signer_nonce, run_progress_consumer, setup_runner,
        },
    },
    cli::SizeDistribution,
    format, interactive,
};

const DEFAULT_RNG_SEED: u64 = 0xFEE5_FEE5_FEE5_FEE5;

/// Size buckets used in the report. Edges are inclusive on the lower bound.
const BUCKETS: &[(u32, u32, &str)] = &[
    (0, 99, "0–99"),
    (100, 199, "100–199"),
    (200, 499, "200–499"),
    (500, 999, "500–999"),
    (1_000, 1_999, "1k–1.99k"),
    (2_000, u32::MAX, "2k+"),
];

#[derive(Clone, Copy)]
struct Sample {
    encoded_size: u32,
    /// Total bond held against the depositor at deposit time (= base + premium).
    bond: u128,
    /// Unmultiplied bond — the part `remove_own` would refund.
    base_bond: u128,
    /// Inclusion fee paid by the depositor.
    tx_fee: u128,
}

impl Sample {
    /// Multiplier surplus permanently lost on `remove_own` / `finalize`.
    /// `bond − base_bond`.
    fn premium(&self) -> u128 {
        self.bond.saturating_sub(self.base_bond)
    }

    /// Total amount leaving the depositor's spendable balance, irrespective
    /// of the refund path: `bond + tx_fee`. Even within the commitment
    /// window the user will get back at most `base_bond` (premium goes to
    /// the Treasury), so the total is what they need to fund.
    fn total_user_cost(&self) -> u128 {
        self.bond.saturating_add(self.tx_fee)
    }
}

/// Inputs for [`run`]. Grouped because the CLI wiring already feeds 11+ fields
/// and a positional list invites permutation bugs at every refactor.
pub struct Args<'a> {
    pub url: &'a str,
    /// `None` triggers the wizard.
    pub count: Option<u32>,
    pub distribution: SizeDistribution,
    pub base_signer: &'a str,
    pub signer_count: u32,
    pub concurrency: u32,
    pub batch_size: u32,
    pub auto_fund: bool,
    pub funder: &'a str,
    pub fund_margin: f64,
    pub fund_batch_size: u32,
    pub rng_seed: Option<u64>,
    pub out: Option<&'a Path>,
    /// Skip the pre-flight confirmation prompt (CI / unattended runs).
    pub assume_yes: bool,
}

pub async fn run(args: Args<'_>) -> Result<()> {
    let Args {
        url,
        count,
        distribution,
        base_signer,
        signer_count,
        concurrency,
        batch_size,
        auto_fund,
        funder,
        fund_margin,
        fund_batch_size,
        rng_seed,
        out,
        assume_yes,
    } = args;

    // Mirror `bench::seed`: build the config from CLI flags (with `count = 0`
    // as a placeholder when missing) and only hand off to the wizard if
    // `count` was omitted. Both paths converge at the destructure below.
    let cfg = interactive::FeesConfig {
        count: count.unwrap_or(0),
        size_distribution: distribution,
        base_signer: base_signer.to_string(),
        signer_count,
        concurrency,
        batch_size,
        auto_fund,
        funder: funder.to_string(),
        fund_margin,
        fund_batch_size,
        rng_seed: rng_seed.unwrap_or(DEFAULT_RNG_SEED),
        out: out.map(PathBuf::from),
    };
    let cfg = if count.is_some() {
        cfg
    } else {
        interactive::fees_wizard(cfg)?
    };

    let interactive::FeesConfig {
        count,
        size_distribution: distribution,
        base_signer,
        signer_count,
        concurrency,
        batch_size,
        auto_fund,
        funder,
        fund_margin,
        fund_batch_size,
        rng_seed,
        out,
    } = cfg;

    if count == 0 {
        println!("count = 0, nothing to do");
        return Ok(());
    }

    let (signer_count, concurrency) = sanitize_signer_concurrency(signer_count, concurrency);
    let batch_size = batch_size.max(1);
    // Auto-fund on a solo `//Alice` run is a no-op (only one signer, already
    // pre-funded) — silently disable it so the CLI flag and the wizard don't
    // surprise users who flipped the toggle without thinking.
    let auto_fund = auto_fund && signer_count > 1;

    println!(
        "bench fees: count={count} distribution={distribution:?} \
         signers={signer_count} concurrency={concurrency} batch_size={batch_size} \
         rng_seed=0x{rng_seed:016x}"
    );
    if signer_count > 1 && !auto_fund {
        println!(
            "  note: derived signers `{base_signer}//1..{base_signer}//{signer_count}` must \
             hold balance — pre-fund via `seed --auto-fund` or pass `--auto-fund` here"
        );
    }

    // Pre-generate all payloads from a single RNG so multi-signer runs stay
    // bit-for-bit reproducible against the single-signer baseline: same
    // (rng_seed, count) ⇒ same `Vec<MusicalWork>` ⇒ same on-chain state.
    let payloads: Vec<MusicalWork> = {
        let mut rng = seeded_rng(rng_seed);
        (0..count)
            .map(|i| payload_for_index(distribution, &mut rng, i))
            .collect()
    };

    let confirm_prompt = if auto_fund {
        format!(
            "About to deposit {count} record(s) over {signer_count} signer(s) and \
             auto-fund them from `{funder}` on `{url}`. Continue?"
        )
    } else {
        format!(
            "About to deposit {count} record(s) over {signer_count} signer(s) on `{url}`. \
             Continue?"
        )
    };

    let RunnerHandles {
        client,
        signers,
        partitions,
        pricing_at_start: snapshot_start,
        ..
    } = setup_runner(RunnerInputs {
        url,
        base_signer: &base_signer,
        signer_count,
        // Solo runs sign with the base URI verbatim so a fresh chain's
        // pre-funded `//Alice` keeps working without auto-fund. Multi-signer
        // flips back into the derivation scheme shared with seed/throughput.
        solo_uses_base_uri: true,
        payloads,
        auto_fund,
        funder: &funder,
        fund_margin,
        fund_batch_size,
        assume_yes,
        confirm_prompt,
    })
    .await?;

    let (tx, rx) = tokio::sync::mpsc::unbounded_channel::<WorkerEvent>();
    let semaphore = Arc::new(Semaphore::new(concurrency as usize));
    let mut set: JoinSet<()> = JoinSet::new();
    let started = Instant::now();
    for (signer_idx, (signer, partition)) in signers.into_iter().zip(partitions).enumerate() {
        if partition.is_empty() {
            continue;
        }
        let semaphore = semaphore.clone();
        let client = client.clone();
        let tx = tx.clone();
        let batch_size_usize = batch_size as usize;
        // Spawn every worker eagerly and have them wait for a concurrency
        // permit *inside* the task. Acquiring before the spawn would serialise
        // the loop on the semaphore: with `concurrency` < `signer_count`, the
        // loop blocks until an existing worker drains its whole partition,
        // which delays the consumer task (spawned after this loop) by tens of
        // minutes — long enough that the user sees "no progress" right after
        // auto-fund and assumes the run is dead.
        set.spawn(async move {
            let _permit = match semaphore.acquire_owned().await {
                Ok(p) => p,
                Err(_) => return,
            };
            let api = client.musical_works();
            let mut nonce = match fetch_signer_nonce(&client, &signer).await {
                Ok(n) => n,
                Err(e) => {
                    let _ = tx.send(WorkerEvent::Failed {
                        signer_idx,
                        error: format!("{e}"),
                    });
                    return;
                }
            };
            let chunk_sizes: Vec<u32> = partition
                .chunks(batch_size_usize)
                .map(|c| c.len() as u32)
                .collect();
            let total_chunks = chunk_sizes.len();
            for (chunk_idx, chunk) in partition.chunks(batch_size_usize).enumerate() {
                // Pre-compute encoded sizes so we can move the chunk into the
                // batch call (the call consumes its `Vec<MusicalWork>`) and
                // still attribute each receipt back to its source size.
                let encoded_sizes: Vec<u32> =
                    chunk.iter().map(|w| w.encoded_size() as u32).collect();
                match api
                    .deposit_batch_with_receipts_nonce(&signer, chunk.to_vec(), nonce)
                    .await
                {
                    Ok(receipts) => {
                        nonce = nonce.saturating_add(1);
                        // The runtime returns one `Deposited` per inner
                        // deposit in submission order, plus one outer
                        // `TransactionFeePaid` — `tx_fee` here is the
                        // amortised per-record share. `bond` / `base_bond`
                        // are exact per-record values (one event each).
                        for (encoded_size, receipt) in encoded_sizes.iter().zip(receipts.iter()) {
                            let tx_fee = receipt.tx_fee.unwrap_or(0);
                            let _ = tx.send(WorkerEvent::Sample(Sample {
                                encoded_size: *encoded_size,
                                bond: receipt.bond,
                                base_bond: receipt.base_bond,
                                tx_fee,
                            }));
                        }
                    }
                    Err(e) => {
                        // Mirror seed / throughput batched: bail the whole
                        // worker on first failure. Continuing is hopeless —
                        // runtime errors (e.g. `BondHoldFailed` when a
                        // signer is broke) consume the nonce, so the chain
                        // advances under us. Re-fetching from finalised
                        // storage lags 2-3 blocks behind best, so the next
                        // submit picks up a stale nonce and rejects as
                        // `Transaction is outdated`. Surviving signers keep
                        // draining their partitions.
                        let remaining_records: u32 = chunk_sizes[chunk_idx..].iter().sum();
                        let remaining_chunks = total_chunks - chunk_idx;
                        let _ = tx.send(WorkerEvent::Failed {
                            signer_idx,
                            error: format!(
                                "stopped at batch {}/{total_chunks}: {e} \
                                 — skipping {remaining_chunks} remaining batch(es) \
                                 ({remaining_records} records)",
                                chunk_idx + 1,
                            ),
                        });
                        let _ = tx.send(WorkerEvent::SkippedRecords {
                            count: remaining_records,
                        });
                        return;
                    }
                }
            }
        });
    }
    // Drop the original sender so `rx.recv()` returns None once every worker
    // has dropped its clone — i.e. the channel naturally closes when the run
    // is complete.
    drop(tx);

    // Single consumer task drains the events stream, owns the progress
    // printer, and accumulates samples. Keeping it on its own task means the
    // main task can `join_next` workers without contending with the printer.
    let consumer = tokio::spawn(run_progress_consumer(
        rx,
        count,
        started,
        FeesConsumerState::new(count),
        |event, st, progress| match event {
            WorkerEvent::Sample(s) => st.samples.push(s),
            WorkerEvent::Failed { signer_idx, error } => {
                progress.clear();
                eprintln!("  signer #{signer_idx}: deposit failed: {error}");
            }
            WorkerEvent::SkippedRecords { count } => {
                st.failed += count;
            }
        },
        |st| {
            let processed = st.samples.len() as u32 + st.failed;
            (processed, st.samples.len() as u32, st.failed)
        },
    ));

    while let Some(joined) = set.join_next().await {
        joined.map_err(|e| anyhow!("worker panicked: {e}"))?;
    }
    let FeesConsumerState { samples, failed } = consumer
        .await
        .map_err(|e| anyhow!("consumer panicked: {e}"))?;
    let duration_ms = started.elapsed().as_millis();

    // Second snapshot taken after the deposit loop so the report can show
    // how much the multipliers / weekly load drifted across the run. We
    // only fail the run if both this and the per-record events were
    // unavailable; a soft snapshot read failure is logged but otherwise
    // ignored — the rest of the report is still valuable.
    let snapshot_end = match client.musical_works().pricing_snapshot().await {
        Ok(s) => Some(s),
        Err(e) => {
            eprintln!("  warning: failed to read end-of-run pricing snapshot: {e}");
            None
        }
    };

    println!(
        "done: {ok}/{count} succeeded, {failed} failed in {duration_ms}ms",
        ok = samples.len(),
    );

    if samples.is_empty() {
        return Err(anyhow!(
            "no successful samples in {failed} skipped record(s) — likely missing funding \
             (pass `--auto-fund` or pre-fund the derived signers) or a runtime error in \
             every batch; re-run after fixing"
        ));
    }

    let ctx = ReportContext {
        url,
        distribution,
        signer_count,
        concurrency,
        batch_size,
        rng_seed,
        count_requested: count,
        count_succeeded: samples.len() as u32,
        count_failed: failed,
        duration_ms,
        snapshot_start,
        snapshot_end,
    };

    match out.as_deref() {
        // Markdown is only worth its noise when the output is going to be
        // committed or pasted somewhere markdown-aware. On stdout the
        // pipe-and-dash table is unreadable, so render an aligned text
        // version with proper column padding instead.
        Some(path) => write_report_to(path, &build_markdown_report(ctx, &samples))?,
        None => println!("\n{}", build_text_report(ctx, &samples)),
    }

    Ok(())
}

enum WorkerEvent {
    /// Per-record receipt extracted from a successful batch.
    Sample(Sample),
    /// Out-of-band log line surfaced above the progress line (one per failed
    /// batch / aborted worker). Doesn't move the failure counter — that's
    /// driven by [`WorkerEvent::SkippedRecords`].
    Failed { signer_idx: usize, error: String },
    /// Records skipped after a worker bailed on its first batch failure.
    /// Counts the failed batch *and* every chunk the worker won't attempt.
    /// Mirrors the shape used by `bench seed`.
    SkippedRecords { count: u32 },
}

/// State accumulated by the consumer task. Promoted out of inline locals so
/// the generic `run_progress_consumer` can return it as a single value.
struct FeesConsumerState {
    samples: Vec<Sample>,
    failed: u32,
}

impl FeesConsumerState {
    fn new(count: u32) -> Self {
        Self {
            samples: Vec::with_capacity(count as usize),
            failed: 0,
        }
    }
}

fn payload_for_index<R: Rng + ?Sized>(
    distribution: SizeDistribution,
    rng: &mut R,
    index: u32,
) -> MusicalWork {
    match distribution {
        SizeDistribution::Real => musical_work::random_with_iswc_index(rng, index),
        SizeDistribution::Max => with_iswc(pathological::max_size_musical_work(), index),
        SizeDistribution::Mixed => match index % 3 {
            0 => with_iswc(pathological::min_size_musical_work(), index),
            1 => musical_work::random_with_iswc_index(rng, index),
            _ => with_iswc(pathological::max_size_musical_work(), index),
        },
    }
}

/// Swap the canonical ISWC of a precomputed work for one derived from `index`.
/// Used to give the size-extreme `pathological` payloads unique identifiers
/// across a batch without rebuilding the rest of the (large) payload.
fn with_iswc(mut work: MusicalWork, index: u32) -> MusicalWork {
    let MusicalWork::V1(v1) = &mut work;
    v1.iswc = iswc_for_index(index);
    work
}

struct ReportContext<'a> {
    url: &'a str,
    distribution: SizeDistribution,
    signer_count: u32,
    concurrency: u32,
    batch_size: u32,
    rng_seed: u64,
    count_requested: u32,
    count_succeeded: u32,
    count_failed: u32,
    duration_ms: u128,
    /// Pricing snapshot taken before the deposit loop starts.
    snapshot_start: PricingSnapshot,
    /// Pricing snapshot taken after the loop. `None` if the post-loop read
    /// failed (e.g. a node restart) — the report still renders the rest.
    snapshot_end: Option<PricingSnapshot>,
}

/// Headers + rows for the aggregate table. Stat values are pre-formatted so
/// renderers (markdown, text) just deal with strings.
const AGGREGATE_HEADERS: &[&str] = &["Metric", "Min", "p50", "p95", "p99", "Max", "Mean"];
/// Headers for the per-bucket table.
const BUCKET_HEADERS: &[&str] = &[
    "Size bucket (bytes)",
    "n",
    "Avg base bond",
    "Avg premium",
    "Avg total bond",
    "Avg tx fee",
    "p50 total cost",
    "p95 total cost",
    "p99 total cost",
];

fn aggregate_rows(samples: &[Sample]) -> Vec<Vec<String>> {
    vec![
        stat_row(
            "encoded size (bytes)",
            samples,
            |s| s.encoded_size as u128,
            |v| v.to_string(),
        ),
        stat_row(
            "base bond (refundable)",
            samples,
            |s| s.base_bond,
            format::plancks,
        ),
        stat_row(
            "premium (to Treasury)",
            samples,
            |s| s.premium(),
            format::plancks,
        ),
        stat_row("total bond (held)", samples, |s| s.bond, format::plancks),
        stat_row("tx fee", samples, |s| s.tx_fee, format::plancks),
        stat_row(
            "total user cost",
            samples,
            |s| s.total_user_cost(),
            format::plancks,
        ),
    ]
}

fn stat_row(
    label: &str,
    samples: &[Sample],
    f: impl Fn(&Sample) -> u128,
    fmt: impl Fn(u128) -> String,
) -> Vec<String> {
    let mut values: Vec<u128> = samples.iter().map(&f).collect();
    values.sort_unstable();
    let min = *values.first().unwrap_or(&0);
    let max = *values.last().unwrap_or(&0);
    let mean: u128 = if values.is_empty() {
        0
    } else {
        values.iter().sum::<u128>() / values.len() as u128
    };
    let p50 = percentile(&values, 0.50);
    let p95 = percentile(&values, 0.95);
    let p99 = percentile(&values, 0.99);
    vec![
        label.to_string(),
        fmt(min),
        fmt(p50),
        fmt(p95),
        fmt(p99),
        fmt(max),
        fmt(mean),
    ]
}

fn bucket_rows(samples: &[Sample]) -> Vec<Vec<String>> {
    let mut out = Vec::new();
    for &(lo, hi, label) in BUCKETS {
        let bucket: Vec<&Sample> = samples
            .iter()
            .filter(|s| s.encoded_size >= lo && s.encoded_size <= hi)
            .collect();
        if bucket.is_empty() {
            continue;
        }
        let mean_base = mean(&bucket, |s| s.base_bond);
        let mean_premium = mean(&bucket, |s| s.premium());
        let mean_bond = mean(&bucket, |s| s.bond);
        let mean_fee = mean(&bucket, |s| s.tx_fee);
        let mut totals: Vec<u128> = bucket.iter().map(|s| s.total_user_cost()).collect();
        totals.sort_unstable();
        let p50 = percentile(&totals, 0.50);
        let p95 = percentile(&totals, 0.95);
        let p99 = percentile(&totals, 0.99);
        out.push(vec![
            label.to_string(),
            bucket.len().to_string(),
            format::plancks(mean_base),
            format::plancks(mean_premium),
            format::plancks(mean_bond),
            format::plancks(mean_fee),
            format::plancks(p50),
            format::plancks(p95),
            format::plancks(p99),
        ]);
    }
    out
}

/// Format a pricing snapshot as a single line: multipliers + weekly load
/// gauge. Used in both markdown and text reports — the format is identical
/// since the values fit on one line.
fn format_snapshot(snap: &PricingSnapshot) -> String {
    let actual = snap.weekly_actual;
    let target = snap.weekly_target;
    let load_pct = if target == 0 {
        0.0
    } else {
        (actual as f64 / target as f64) * 100.0
    };
    format!(
        "M_fast={:.4}× M_slow={:.4}× weekly={}/{} ({:.1}%)",
        fixed_u128_to_f64(snap.fast_multiplier),
        fixed_u128_to_f64(snap.slow_multiplier),
        actual,
        target,
        load_pct,
    )
}

fn build_markdown_report(ctx: ReportContext<'_>, samples: &[Sample]) -> String {
    let ReportContext {
        url,
        distribution,
        signer_count,
        concurrency,
        batch_size,
        rng_seed,
        count_requested,
        count_succeeded,
        count_failed,
        duration_ms,
        snapshot_start,
        snapshot_end,
    } = ctx;
    let mut out = String::new();
    let _ = writeln!(out, "# `bench fees` report\n");
    let _ = writeln!(out, "- node: `{url}`");
    let _ = writeln!(out, "- distribution: `{distribution:?}`");
    let _ = writeln!(out, "- signers: {signer_count} (concurrency={concurrency})");
    let _ = writeln!(out, "- batch size: {batch_size}");
    let _ = writeln!(out, "- rng seed: `0x{rng_seed:016x}`");
    let _ = writeln!(
        out,
        "- count: requested={count_requested}, succeeded={count_succeeded}, failed={count_failed}"
    );
    let _ = writeln!(out, "- wall time: {duration_ms} ms");
    let _ = writeln!(
        out,
        "- pricing (start): `{}`",
        format_snapshot(&snapshot_start)
    );
    if let Some(end) = snapshot_end {
        let _ = writeln!(out, "- pricing (end): `{}`", format_snapshot(&end));
    } else {
        let _ = writeln!(out, "- pricing (end): _unavailable (post-run RPC failed)_");
    }
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "## Aggregate (all successful samples)\n\n\
         _Token amounts shown with the chain's 12 decimals; trailing zeros trimmed._\n\
         _`base bond` is refundable via `remove_own` within 7 days; `premium` is the\n\
         multiplier surplus permanently routed to the Foundation Treasury._\n\
         _`tx fee` is the per-record share of the outer `Utility::batch_all` fee\n\
         (one `TransactionFeePaid` event per batch, divided by batch_size)._\n"
    );
    render_markdown_table(&mut out, AGGREGATE_HEADERS, &aggregate_rows(samples));

    let _ = writeln!(out, "\n## By payload size\n");
    render_markdown_table(&mut out, BUCKET_HEADERS, &bucket_rows(samples));

    out
}

fn build_text_report(ctx: ReportContext<'_>, samples: &[Sample]) -> String {
    let ReportContext {
        url,
        distribution,
        signer_count,
        concurrency,
        batch_size,
        rng_seed,
        count_requested,
        count_succeeded,
        count_failed,
        duration_ms,
        snapshot_start,
        snapshot_end,
    } = ctx;
    let mut out = String::new();
    let _ = writeln!(out, "bench fees report");
    let _ = writeln!(out, "  node:        {url}");
    let _ = writeln!(out, "  distribution: {distribution:?}");
    let _ = writeln!(
        out,
        "  signers:     {signer_count} (concurrency={concurrency})"
    );
    let _ = writeln!(out, "  batch size:  {batch_size}");
    let _ = writeln!(out, "  rng seed:    0x{rng_seed:016x}");
    let _ = writeln!(
        out,
        "  count:       requested={count_requested}, succeeded={count_succeeded}, failed={count_failed}"
    );
    let _ = writeln!(out, "  wall time:   {duration_ms} ms");
    let _ = writeln!(out, "  pricing(s):  {}", format_snapshot(&snapshot_start));
    match snapshot_end {
        Some(end) => {
            let _ = writeln!(out, "  pricing(e):  {}", format_snapshot(&end));
        }
        None => {
            let _ = writeln!(out, "  pricing(e):  unavailable (post-run RPC failed)");
        }
    }
    let _ = writeln!(
        out,
        "  (token amounts use the chain's 12 decimals; trailing zeros trimmed)"
    );
    let _ = writeln!(
        out,
        "  (base bond = refundable via `remove_own`; premium = to Treasury;\n\
           tx fee = amortised per-record share of the outer batch_all fee)"
    );
    let _ = writeln!(out, "\nAggregate (all successful samples)");
    render_text_table(&mut out, AGGREGATE_HEADERS, &aggregate_rows(samples));
    let _ = writeln!(out, "\nBy payload size");
    render_text_table(&mut out, BUCKET_HEADERS, &bucket_rows(samples));
    out
}

fn render_markdown_table(out: &mut String, headers: &[&str], rows: &[Vec<String>]) {
    let _ = writeln!(out, "| {} |", headers.join(" | "));
    let _ = writeln!(
        out,
        "|{}|",
        std::iter::repeat_n("---|", headers.len()).collect::<String>()
    );
    for row in rows {
        let _ = writeln!(out, "| {} |", row.join(" | "));
    }
}

/// Render a fixed-width table for terminal output: first column
/// left-aligned for labels, every other column right-aligned for numbers.
/// Column widths are sized to the widest cell (header included) so values
/// always fit cleanly without truncation.
fn render_text_table(out: &mut String, headers: &[&str], rows: &[Vec<String>]) {
    let cols = headers.len();
    let mut widths: Vec<usize> = headers.iter().map(|h| h.len()).collect();
    for row in rows {
        for (i, cell) in row.iter().enumerate().take(cols) {
            widths[i] = widths[i].max(cell.len());
        }
    }
    let pad_cell = |out: &mut String, i: usize, cell: &str| {
        if i == 0 {
            let _ = write!(out, "  {cell:<w$}", w = widths[i]);
        } else {
            let _ = write!(out, "  {cell:>w$}", w = widths[i]);
        }
    };
    for (i, h) in headers.iter().enumerate() {
        pad_cell(out, i, h);
    }
    out.push('\n');
    let total = widths.iter().sum::<usize>() + 2 * cols;
    let _ = writeln!(out, "  {}", "-".repeat(total.saturating_sub(2)));
    for row in rows {
        for (i, cell) in row.iter().enumerate().take(cols) {
            pad_cell(out, i, cell);
        }
        out.push('\n');
    }
}
