//! Weight definitions for `pallet-midds`.
//!
//! The pallet ships only the [`WeightInfo`] trait and a zero-weight impl for
//! tests. Integrating runtimes are expected to generate their own impl by
//! running the benchmarks in `benchmarking.rs` against their own runtime /
//! hardware — shipping placeholder numbers here would risk a runtime author
//! deploying with fake weights that look autogenerated.

use frame_support::weights::Weight;

/// Per-extrinsic weight functions. `s` is the SCALE-encoded payload size in
/// bytes when relevant; the per-block `on_initialize` cost is split into a
/// fixed base plus `n × finalize_one()` so a runtime can pick a sensible
/// `MaxFinalizationsPerBlock` from the headroom of its target block weight.
pub trait WeightInfo {
    fn deposit(s: u32) -> Weight;
    fn deposit_on_behalf(s: u32) -> Weight;
    fn update(s: u32) -> Weight;
    fn update_on_behalf(s: u32) -> Weight;
    fn remove_own() -> Weight;
    fn remove_own_on_behalf() -> Weight;
    fn finalize_one() -> Weight;
    fn force_edit(s: u32) -> Weight;
    fn force_remove_refund() -> Weight;
    fn force_remove_slash() -> Weight;
    fn force_remove_many(n: u32) -> Weight;
}

/// Zero-weight impl, suitable for unit tests and mock runtimes only.
impl WeightInfo for () {
    fn deposit(_s: u32) -> Weight {
        Weight::zero()
    }
    fn deposit_on_behalf(_s: u32) -> Weight {
        Weight::zero()
    }
    fn update(_s: u32) -> Weight {
        Weight::zero()
    }
    fn update_on_behalf(_s: u32) -> Weight {
        Weight::zero()
    }
    fn remove_own() -> Weight {
        Weight::zero()
    }
    fn remove_own_on_behalf() -> Weight {
        Weight::zero()
    }
    fn finalize_one() -> Weight {
        Weight::zero()
    }
    fn force_edit(_s: u32) -> Weight {
        Weight::zero()
    }
    fn force_remove_refund() -> Weight {
        Weight::zero()
    }
    fn force_remove_slash() -> Weight {
        Weight::zero()
    }
    fn force_remove_many(_n: u32) -> Weight {
        Weight::zero()
    }
}
